// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseSpinner: typeof import('./components/BaseSpinner.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  }
}

export { }
