// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseCheckboxGroup: typeof import('./components/BaseCheckboxGroup.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseListbox: typeof import('./components/BaseListbox.vue')['default']
    BaseRadioGroup: typeof import('./components/BaseRadioGroup.vue')['default']
    BaseRadioGroupOption: typeof import('./components/BaseRadioGroupOption.vue')['default']
    BaseSpinner: typeof import('./components/BaseSpinner.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HSwitch: typeof import('@headlessui/vue')['Switch']
    HSwitchGroup: typeof import('@headlessui/vue')['SwitchGroup']
    HSwitchLabel: typeof import('@headlessui/vue')['SwitchLabel']
    IHeroiconsOutlineCloudUpload: typeof import('~icons/heroicons-outline/cloud-upload')['default']
    IHeroiconsOutlineHome: typeof import('~icons/heroicons-outline/home')['default']
    IHeroiconsSolidBeaker: typeof import('~icons/heroicons-solid/beaker')['default']
  }
}

export { }
