// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    BaseListbox: typeof import('./components/BaseListbox.vue')['default']
    BaseSpinner: typeof import('./components/BaseSpinner.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    HListbox: typeof import('@headlessui/vue')['Listbox']
    HListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    HListboxLabel: typeof import('@headlessui/vue')['ListboxLabel']
    HListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    HListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    HSwitch: typeof import('@headlessui/vue')['Switch']
    IHeroiconsOutlineCloudUpload: typeof import('~icons/heroicons-outline/cloud-upload')['default']
    IHeroiconsOutlineMoon: typeof import('~icons/heroicons-outline/moon')['default']
    IHeroiconsSolidBeaker: typeof import('~icons/heroicons-solid/beaker')['default']
    IHeroiconsSolidCheck: typeof import('~icons/heroicons-solid/check')['default']
    IHeroiconsSolidExclamationCircle: typeof import('~icons/heroicons-solid/exclamation-circle')['default']
    IHeroiconsSolidSelector: typeof import('~icons/heroicons-solid/selector')['default']
  }
}

export { }
